# Generated by Django 4.2.6 on 2023-11-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_events_alter_faculty_email_alter_student_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='exam',
        ),
    ]
