# Generated by Django 4.2.6 on 2023-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_events_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
