# Generated by Django 4.2.6 on 2023-11-26 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Session must be in the format "YYYY-YYYY"', regex='^\\d{4}-\\d{4}$')]),
        ),
    ]
