# Generated by Django 4.2.6 on 2023-11-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_exam_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='admit_card',
        ),
    ]
