# Generated by Django 4.2.6 on 2023-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_uploadedimage_delete_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetabledata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('time_table_url', models.URLField()),
            ],
        ),
    ]
