# Generated by Django 4.2.6 on 2023-11-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_timetabledata_time_table_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=100)),
                ('question1', models.IntegerField()),
                ('question2', models.IntegerField()),
                ('question3', models.IntegerField()),
                ('question4', models.IntegerField()),
                ('question5', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='login.student')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='login.subjects')),
            ],
        ),
    ]
