# Generated by Django 4.2.6 on 2023-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_feedbacktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
